version: '3.2'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Duda
      MONGO_INITDB_ROOT_PASSWORD: M@ri@eduarda

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Duda
      ME_CONFIG_MONGODB_ADMINPASSWORD: M@ri@eduarda